-- ========================================================
-- 1. Inserts para la Tabla Productos (con la columna imagen incluida)
-- ========================================================
INSERT INTO productos(nombre, marca, especie, stock, costo, precio_venta, visibilidad, destacado, descripcion, imagen) VALUES
("Mezcla Nutridor 25kg", "El nogal", "Bovinos", 20, 200, 300, 1, 1, "Alimento balanceado de alta tecnología para vacas altas productoras. Elaborado con ingredientes de alta calidad.", "recursos-graficos/productos/bovino/bovino-adm-mezcla-nutridor.png"),
("Mezcla Ganadera 25kg", "ADM", "Bovinos", 20, 200.00, 279.00, 1, 1, "Alimento balanceado de alta tecnología para la engorda de bovinos. Elaborado con ingredientes de alta calidad.", "recursos-graficos/productos/bovino/bovino-adm-mezcla-ganadera-malta.png"),
("Pollo Especial 25kg", "ADM", "Aves", 20, 200.00, 245.00, 1, 0, "Alimento balanceado de alta tecnología para pollitos de engorda. Elaborado con ingredientes de alta calidad.", "recursos-graficos/productos/aves/aves-adm-pollo-especial.png"),
("Nutridor Pollos 25kg", "ADM", "Aves", 20, 200.00, 245.00, 1, 0, "Alimento balanceado de alta tecnología para pollitos de engorda. Elaborado con ingredientes de alta calidad.", "recursos-graficos/productos/aves/aves-adm-pollo-nutridor.png"),
("Finalizador® Engorda Cerdos H.L. 25kg", "ADM", "Porcinos", 20, 200.00, 286.00, 1, 1, "Alimento balanceado de alta tecnología para cerdos en finalización de la engorda de 78 a 104 kg.", "recursos-graficos/productos/porcino/porcino-adm-engorda.png"),
("Growpig!® Desarrollo 25kg", "ADM", "Porcinos", 20, 200.00, 286.00, 1, 0, "Alimento balanceado de alta tecnología para cerdos en engorda de 52 a 76 kg.", "recursos-graficos/productos/porcino/porcino-adm-growpig.png"),
("Borregos Forte 25kg", "ADM", "Ovinos", 20, 200.00, 269.00, 1, 0, "Alimento balanceado de alta tecnología para ovinos en etapa de engorda y finalización. Elaborado con ingredientes de alta calidad.", "recursos-graficos/productos/ovino/ovino-adm-borrego-forte.png"),
("Borrego Ganador 25kg", "ADM", "Ovinos", 20, 200.00, 269.00, 1, 0, "Alimento balanceado de alta tecnología para ovinos en etapa de crecimiento. Elaborado con ingredientes de alta calidad.", "recursos-graficos/productos/ovino/ovino-adm-borrego-ganador.png"),
("Engorda Ganado 25kg", "El Nogal", "Bovinos", 20, 200.00, 410.00, 1, 1, "Alimento balanceado para bovinos de engorda de corral.", "recursos-graficos/productos/bovino/bovino-nogal-engorda.png"),
("Concentrado para Engorda Ganado 25kg", "El Nogal", "Bovinos", 20, 200.00, 410.00, 1, 0, "Concentrado alimenticio para ganado bovino de engorda.", "recursos-graficos/productos/bovino/bovino-nogal-concentrado-engorda.png"),
("Fortipollo (iniciador) 25kg", "El Nogal", "Aves", 20, 200.00, 438.00, 1, 0, "Alimento completo para pollos de engorda ofrezca desde el nacimiento hasta el final de la tercer semana (del dí­a 1 hasta el dí­a 21 de edad).", "recursos-graficos/productos/aves/aves-nogal-fortipollo.png"),
("Maxipollo (engorda) 25kg", "El Nogal", "Aves", 20, 200.00, 245.00, 1, 1, "Alimento completo para pollos de engorda que se ofrece desde el inicio de la cuarta semana y hasta el final de la sexta semana (del dí­a 22 al hasta el dí­a 42 de edad).", "recursos-graficos/productos/aves/aves-nogal-maxipollo.png"),
("Engorda 25kg", "El Nogal", "Porcinos", 20, 200.00, 369.00, 1, 1, "Alimento completo para cerdos en finalización.", "recursos-graficos/productos/porcino/porcino-nogal-engorda.png"),
("Crecimiento 25kg", "El Nogal", "Porcinos", 20, 200.00, 644.00, 1, 0, "Alimento completo para cerdos de 30 a 60 kg de 'peso vivo'.", "recursos-graficos/productos/porcino/porcino-nogal-crecimiento.png"),
("Preiniciador Borrego 25kg", "El Nogal", "Ovinos", 20, 200.00, 525.00, 1, 0, "Alimento balanceado para ofrecer a borregos desde una semana de edad y hasta el destete.", "recursos-graficos/productos/ovino/ovino-nogal-preiniciador.png"),
("Borrego Engorda 25kg", "El Nogal", "Ovinos", 20, 200.00, 525.00, 1, 0, "Alimento integral para ofrecer a libre acceso a borregos en engorda intensiva.", "recursos-graficos/productos/ovino/ovino-nogal-engorda.png"),
("Ara H Engorda Ganado 12% Rol 25kg", "Alimentos Arandas", "Bovinos", 20, 200.00, 750.00, 1, 1, "Alimento Balanceado, multiparticula, mezcla de harina y maíz rolado para bovinos de engorda.", "recursos-graficos/productos/bovino/bovino-aranda-engorda.png"),
("Ara P Crecimiento Becerra 25kg", "Alimentos Arandas", "Bovinos", 20, 200.00, 750.00, 1, 0, "Alimento balanceado, multipartícula, mezcla de harina y maíz rolado, diseñado para la etapa de desarrollo y crecimiento de becerras.", "recursos-graficos/productos/bovino/bovino-aranda-crecimiento.png"),
("Ara M Inipollo 25kg", "Alimentos Arandas", "Aves", 20, 200.00, 770.00, 1, 0, "Alimento Balanceado presentación en migaja para pollitos de engorda desde el nacimiento hasta los 21 días de edad.", "recursos-graficos/productos/aves/aves-aranda-inipollo.png"),
("Ara Sostenedor 25kg", "Alimentos Arandas", "Aves", 20, 200.00, 770.00, 1, 0, "Alimento Balanceado presentación en migaja para pollos de engorda desde los 21 días de edad al mercado.", "recursos-graficos/productos/aves/aves-aranda-sostenedor.png"),
("Ara H Crecicerdos 25kg", "Alimentos Arandas", "Porcinos", 20, 200.00, 750.00, 1, 0, "Alimento Balanceado, presentación en harina para Cerdos de 31 kg  a 60 kg.", "recursos-graficos/productos/porcino/porcino-aranda-crecicerdo.png"),
("Ara P Destete Cerdos 25 KG", "Alimentos Arandas", "Porcinos", 20, 200.00, 750.00, 1, 0, "Alimento balanceado, presentación en pellet, diseñado para lechones en la etapa de destete y transición.", "recursos-graficos/productos/porcino/porcino-aranda-destete.png"),
("Ara P Borrego Engorda 25 KG", "Alimentos Arandas", "Ovinos", 20, 200.00, 750.00, 1, 0, "Alimento en pellet para Borregos de engorda de producciones intensivas.", "recursos-graficos/productos/ovino/ovino-borrego-engorda.png"),
("Ara H Borrego Engorda Rol Plus 25kg", "Alimentos Arandas", "Ovinos", 20, 200.00, 750.00, 1, 1, "Alimento multipartícula, mezcla de harina y maíz rolado para borregos de engorda de producciones intensivas.", "recursos-graficos/productos/ovino/ovino-borrego-iniciador.png");